thanos-io/objstore

- README.md
- client/factory.go
- clientutil/parse.go
- clientutil/parse_test.go
- go.mod
- go.sum
- objstore.go
- objstore_test.go
- objtesting/foreach.go
- providers/azure/azure.go
- providers/azure/azure_test.go
- providers/azure/helpers.go
- providers/cos/cos.go
- providers/cos/cos_test.go
- providers/filesystem/filesystem.go
- providers/gcs/gcs_test.go
- providers/oss/oss.go
- providers/s3/s3.go
- providers/s3/s3_e2e_test.go
- providers/s3/s3_test.go
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>
https://github.com/thanos-io/thanos/pull/5474
https://github.com/thanos-io/thanos/pull/5475
https://github.com/thanos-io/thanos/pull/5451
> chore: Sync with upstream Thanos

- providers/azure/azure.go
This change adds a log when the MSI Resource is set in the Azure configuration. The purpose is to make end users aware of the deprecation so that they stop configuring this parameter.
Built a fork that I tested in my own cluster.
> Log deprecation notice when MSI Resource is configured for Azure

- CHANGELOG.md
- providers/s3/s3.go
- providers/s3/s3_test.go
For https://github.com/thanos-io/thanos/issues/5663, enable specifying S3 storage class by specifying it in config.put_user_metadata. For example launching the sidecar with a `--objstore.config-file` as follows stores all S3 files with storage class of ` STANDARD_IA`
```yaml
type: S3
prefix: thanos-test-standard-ia
config:
endpoint: s3.us-east-1.amazonaws.com
region: us-east-1
bucket: MY_BUCKET
put_user_metadata:
X-Amz-Storage-Class: STANDARD_IA
trace:
enable: true
```
while using the following config file uses the default storage class of `STANDARD`
```yaml
type: S3
prefix: thanos-test-standard-ia
config:
endpoint: s3.us-east-1.amazonaws.com
region: us-east-1
bucket: MY_BUCKET
trace:
enable: true
```
Added unit tests.
Manual tests launching the sidecar with the two configurations listed …
> S3: Support specifying S3 storage class

- CHANGELOG.md
- tracing/tracing.go
Currently it's not possible to set the `tracerKey` expected by the package to get the object store client tracing work. In this PR I'm adding the function `ContextWithTracer()` which is a copy of the Thanos one. Then, in Thanos, we can remove the function is use this one instead.
Fixes #30
N/A
> Add ContextWithTracer()

- CHANGELOG.md
- providers/azure/helpers.go
Set client options when creating a Azure client with shared key. Before this the option was only set to clients using MSI authentication.
Should not require verification as the same option is passed to the MSI client.
> azure: Fix ignored options when creating shared credential Azure client

- CHANGELOG.md
- providers/s3/s3.go
- providers/s3/s3_test.go
Fixes #17 
* s3: add support for session token
> s3: add support for session token

- inmem.go
Add locking and return a copy of the internally stored objects in InMemBucket. This fixes a race condition that can be triggered if the result of `.Objects()` is read while another goroutine modifies the objects (such as uploading a new file).
Noticed in grafana/mimir#4021
Signed-off-by: Nick Pillitteri <nick.pillitteri@grafana.com>
Tested repeatedly in a Mimir checkout and was unable to trigger the race condition:
```
go test -race -run=TestDeleteTenant -count=100 ./pkg/compactor/
```
> Add defensive copy of objects in InMemBucket

- CHANGELOG.md
- providers/filesystem/filesystem.go
- providers/filesystem/filesystem_test.go
Changed all of the `filesystem.Bucket` methods to return early if the context has been cancelled.
This makes testing cancellation behaviour of consuming applications easier (see https://github.com/grafana/mimir/pull/4061 for an example), and brings the behaviour of the filesystem bucket into line with the other providers.
I've added tests for cancellation behaviour in `filesystem_test.go`, and the existing acceptance tests should catch any regressions in existing behaviour.
> filesystem: abort filesystem bucket operations if the context has been cancelled

- CHANGELOG.md
- objstore.go
- objstore_test.go
We are using a cloud provider which bills us on the outgoing trafic, so it is useful for me to know how many bytes are downloaded from the bucket.
I thought maybe others can have the same needs.
Of course if you think that could be useful but want a different implementation, let me know.
updated `TestDownloadUploadDirConcurrency` test in `objstore_test.go` but I can add more tests if you want.
Thanks,
> Add new metric to count total number of fetched bytes from bucket

- CHANGELOG.md
- inmem.go
- objstore.go
- prefixed_bucket.go
- providers/azure/azure.go
- providers/bos/bos.go
- providers/cos/cos.go
- providers/filesystem/filesystem.go
- providers/gcs/gcs.go
- providers/obs/obs.go
- providers/oci/oci.go
- providers/oss/oss.go
- providers/s3/s3.go
- providers/swift/swift.go
- testing.go
- tracing.go
Some bucket like [s3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html) and [Azure](https://learn.microsoft.com/en-us/azure/storage/common/customer-managed-keys-overview) implementations allows encrypting the block storage with customer managed keys and the permissions to this keys can be revoked anytime.
This PR is creating a extra method (`IsCustomerManagedKeyError`) when the key permission got revoked by the key owner and so the upstream can handle it appropriately (cortex,thanos)
Related to: https://github.com/cortexproject/cortex/pull/5420
As a first step only the s3 implementation is identifying such errors but i can follow up with the azure one.
* [ X] I added CHANGELOG entry for this change.
* Add `IsCustomerManagedKeyError` method on the bucket …
> Implementing check to identify CMK errors (s3)

- CHANGELOG.md
- providers/s3/s3.go
This PR returns `ctx.Err()` from the S3 `Iter` method instead of `nil` after exhausting the `ListObjects` channel.
When the context passed to the S3 Iter method is cancelled, the underlying Minio client sometimes immediately [closes the results channel](https://github.com/grafana/mimir/blob/285fa4e35dd5720e38dd0491f6ddeb51e3e81197/vendor/github.com/minio/minio-go/v7/api-list.go#L100) and returns without sending the `ctx.Err()` error. Depending on [when exactly the context is cancelled](https://github.com/grafana/mimir/blob/285fa4e35dd5720e38dd0491f6ddeb51e3e81197/vendor/github.com/minio/minio-go/v7/api-list.go#L114-L136), this can result in the `Iter` method not returning any results _and_ not returning an error indicating what happened.
Discovered while debugging grafana/mimir#5433 …
> S3: Return context cancellation from Iter when applicable

- objstore.go
- objstore_test.go
This will allow to understand the distribution of object store fetches.
The metric has been purposely named so it can in the future also cover uploads. #66
> Use a histogram to record transferred bytes for get get_range

- CHANGELOG.md
- README.md
- inmem.go
- objstore.go
- prefixed_bucket.go
- providers/azure/azure.go
- providers/bos/bos.go
- providers/cos/cos.go
- providers/filesystem/filesystem.go
- providers/gcs/gcs.go
- providers/obs/obs.go
- providers/oci/oci.go
- providers/oss/oss.go
- providers/s3/s3.go
- providers/swift/swift.go
- testing.go
- tracing/opentelemetry/opentelemetry.go
- tracing/opentracing/opentracing.go
This PR replace the `IsCustomerManagedKeyError` method for a more generic `IsAccessDeniedErr` method and implement it multiples provides.
This method can be useful for the projects consuming this lib to identify AccessDenied errors from other types of errors and for, for example, avoid retries.
I think is safe to remove the `IsCustomerManagedKeyError` for now as is a [very recent change](https://github.com/thanos-io/objstore/pull/59) and is being used only in cortex for now.
* Remove the `IsCustomerManagedKeyError` method from the objstore interface
* Add `IsAccessDeniedErr` method on the objstore interface and implement it on multiples providers.
> Replace method `IsCustomerManagedKeyError` for a more generic `IsAccessDeniedErr` on the bucket interface.

- CHANGELOG.md
- objstore.go
Аdded file path to erros from DownloadFile
checked error message
> Added file path to erros from DownloadFile

- CHANGELOG.md
- README.md
- providers/azure/azure.go
- providers/azure/azure_test.go
- providers/azure/helpers.go
Added an additional option `storage_connection_string` to Azure config to use a connection string rather than a key.  This is needed in limited privilege scenarios where only a SAS token is available and not  full access key.  When provided, the value is forwarded on to the Azure SDK method for creating a client that accepts a connection string.  
Existing consumers will be unaffected as using this new path must be opted into with a non-empty value for the new config option.
Using a connection string with a SAS token creates a client successfully.  Further verified that running a patched version of loki consuming this library passing through SAS tokens as the authentication method works.
> azure: Support using connection string authentication

- CHANGELOG.md
- providers/gcs/gcs.go
Uses [Query.SetAttrSelection](https://pkg.go.dev/cloud.google.com/go/storage#Query.SetAttrSelection) to only populate the `Name` field in `Iter` for GCS since it's the only object field used. It is suggested in the documentation near the bottom of this [section](https://pkg.go.dev/cloud.google.com/go/storage?utm_source=godoc#hdr-Listing_objects). In case it confuses anyone else besides me `Prefix` isn't an option available to set ([reference](https://github.com/googleapis/google-cloud-go/blob/134e37b184cb8fcec1c93a4cd53df3cf60280dc9/storage/storage.go#L1561)) and isn't affected. 
Locally performed recursive and non-recursive listings both with this change and without against a development bucket. The listing results were identical. I did not attempt to measure a performance impact myself.
> GCS: use Query.SetAttrSelection when listing objects

- CHANGELOG.md
- objstore.go
In metricBucket's `Upload` the reader was being wrapped with `io.NopCloser`, but `newTimingReadCloser` will call `TryToGetSize` [here](https://github.com/thanos-io/objstore/blob/eb06103887ab787f47d08e8a2f100264087319d5/objstore.go#L671) and then get an error.
I noticed this because I saw this in a test's log message ([reference](https://github.com/grafana/mimir/actions/runs/6227135443/job/16905081839?pr=6061))
```
21:56:01 alertmanager-1: ts=2023-09-18T21:56:01.855369927Z caller=s3.go:487 level=warn msg="could not guess file size for multipart upload; upload might be not optimized" name=alertmanager/user-1/fullstate err="unsupported type of io.Reader: io.nopCloserWriterTo"
```
Introduced in https://github.com/thanos-io/objstore/pull/66#discussion_r1287041954
Stepped through a throwaway …
> Fix metricBucket losing object size in Upload

- CHANGELOG.md
- providers/s3/s3.go
When pulling in the latest objstore in a Mimir PR (https://github.com/grafana/mimir/pull/6061) the tests ran into a data race:
<details> <summary> Logs </summary>
```
21:56:02 alertmanager-1: ==================
21:56:02 alertmanager-1: WARNING: DATA RACE
21:56:02 alertmanager-1: Read at 0x00c0007b32f0 by goroutine 524:
21:56:02 alertmanager-1: runtime.mapiterinit()
21:56:02 alertmanager-1: /usr/local/go/src/runtime/map.go:816 +0x0
21:56:02 alertmanager-1: github.com/minio/minio-go/v7.PutObjectOptions.validate()
21:56:02 alertmanager-1: /__w/mimir/mimir/vendor/github.com/minio/minio-go/v7/api-put-object.go:227 +0x66
21:56:02 alertmanager-1: github.com/minio/minio-go/v7.(*Client).PutObject()
21:56:02 alertmanager-1: /__w/mimir/mimir/vendor/github.com/minio/minio-go/v7/api-put-object.go:277 …
```
> S3: clone putUserMetadata map to prevent concurrent modification

- CHANGELOG.md
- go.mod
- go.sum
- objstore.go
Trying to get some statistics in Mimir about the time we're spending in our `iter` operations I realised that despite these operations showing up as part of the labels their value was always 0.
Soon enough and with the help of Peter, I realised that these were not wired up in `objstore.go`.
This PR does exactly that and measures the duration of the whole `iter` operation. There's one big caveat though, `iter` operations take a callback as an argument which is executed per each item returned. The computed duration will include whatever time we spend on each of these callbacks which might an undesirable effect for users of the library.
Sadly, I can't get around this without changing the interface for `iter` to (e.g.) return JUST the time the network operation took. In the meantime, I've …
> Metrics: Wire up `objstore_bucket_operation_duration_seconds` in `iter` operations

- CHANGELOG.md
- providers/s3/s3.go
https://github.com/thanos-io/thanos/pull/6746 bumped objstore, which bumped minio, which made Thanos incompatible with otherwise compliant S3 backends that do not support the x-amz-checksum header.
- Add in a `PutWithMD5` (open to naming changes) config entry to the S3 bucket config that allows turning off this header so that Thanos supports these backends.
Running this at Cloudflare on our [r2](https://developers.cloudflare.com/r2/) backed Thanos that doesn't support this header
> s3: Allow turning off checksums in S3 Puts

- CHANGELOG.md
- README.md
- providers/gcs/gcs.go
GCP has an experimental feature which allows using gRPC when talking to GCS. For the time being, it requires buckets to be explicitly added to an allowlist, but eventually the feature will become GA.
This commit allows using a gRPC client when creating a GCS bucket by toggling a boolean flag in the bucket config.
* Allow using gRPC for GCS buckets.
> Enable using gRPC client for GCS

- CHANGELOG.md
- objstore.go
- objstore_test.go
Cortex uses objstore to update blocks to s3. Cortex had added a retry functionality using seeker objects.
https://github.com/cortexproject/cortex/blob/master/pkg/storage/bucket/s3/bucket_client.go#L176-L191
It checks if an object is seeker and if so it allow it to retry. 
It also wrap the bucket store with metrics
https://github.com/cortexproject/cortex/blob/master/pkg/storage/bucket/client.go#L145
With the new timing metrics, ojbstore now override the object and thus change it to always be io.ReadCloser which is what the implementation requires, but it does not allow cortex to retry request anymore.
The change allow it to continue using a seeker object if the original object was seekable.
Added unit tests to verify the functionality still works.
> Allow timingReadCloser to be seeker

- objstore.go
- objstore_test.go
The PR https://github.com/thanos-io/objstore/pull/66 introduced a regression in the S3 upload performance. After that commit, S3 uploaded are significantly slower. Here you can see how the upload latency changed for one of our Grafana Mimir clusters running in AWS:
_Change deployed to prod on 10/06, where the latency increase. Since the upload performance in Mimir is not critical (e.g. doesn't affect neither read and write path latency), it was undetected for quite some time. Until today._
## The cause
Why the regression? Minio has some optimizations when the reader implements `io.ReaderAt` because it can leverage on `.ReadAt()`. We're used to call `Upload()` with `os.File` as a reader (I think Thanos does the same). After https://github.com/thanos-io/objstore/pull/66 wrapped the reader …
> Fix s3 upload performance regression

- CHANGELOG.md
- providers/swift/swift.go
- providers/swift/swift_test.go
Adding HTTP Config to swift, similar to other providers, in order to support hedging & TLS
cc @JoaoBraveCoding
> Swift: Add HTTP_Config

- providers/gcs/gcs.go
- providers/gcs/gcs_test.go
> GCS: Fix logic for falling back to Google defaults

- CHANGELOG.md
- objstore.go
- objstore_test.go
This PR fixes an issue where the `objstore_bucket_operation_failures_total` metric is incremented if the context is cancelled while reading an object from a bucket but after the `Get` or `GetRange` method has returned.
This makes the behaviour consistent with other operations, and makes the behaviour consistent with a cancellation that occurs while `Get` or `GetRange` is executing.
I have added unit tests to cover this scenario.
> metrics: don't increment `objstore_bucket_operation_failures_total` if context cancelled while reading

- CHANGELOG.md
- README.md
- providers/s3/s3.go
* s3: add DisableMultipart option to force disabling multipart all together.
Checked that the uploaded object was not upload with multipart
> s3: add DisableMultipart option

- CHANGELOG.md
- providers/azure/azure.go
In some cases account does not have permissions to read container properties or create one but has all permissions to do CRUD operations inside the container, e.g SAS tokens. To solve such use case the new configuration property was added for the Azure object storage config which creates a new container explicitly by settings `storage_create_container` to `true` or `false`. To keep backward compatibility with existing object storage configurations the default value for it is always `true`.
azure: Add new storage_create_container configuration property
> azure: Add new storage_create_container configuration property

- CHANGELOG.md
- providers/gcs/gcs.go
- providers/gcs/gcs_test.go
This PR add support for custom `ChunkSize` when uploading object via GCS writer. https://pkg.go.dev/google.golang.org/cloud/storage#Writer
Add test case to make sure newly added config is parsed correctly.
> feat(gcs): Add support for `chunkSize` for writer

- CHANGELOG.md
- objstore.go
- objstore_test.go
- providers/oci/oci.go
Currently if a single process uses multiple object client, we get metrics duplicate registration failures.
With this PR,
1. New `BucketMetrics` API return just a `Metrics` that can be created once and used for multiple clients.
2. New `Wrap` API that takes `metrics` and returns instrumented bucket just like `WrapWithMetrics` API.
This PR doesn't change any existing API `WrapWithMetrics`
Not breaking any existing API(s). All existing tests passes
> feat: Decouple creating bucket metrics from instrumenting the bucket

- objstore.go
This commit adds support for the WriterTo interface in the TimingReader so that it can be used efficiently in io.Copy.
> Add support for WriterTo in TimingReader

- objstore.go
- objstore_test.go
Some objstore providers like s3 do one initial read that already talks to object storage, this read might fail due to timeout, which is invisible in the current instrumentation since only subsequent reads are instrumented. This PR fixes this.
> fix: timing reader ignores initial get_range

- providers/s3/s3.go
Exposing minio client so that it can be used for accessing other methods of minio client library. One of the use case is for generating presigned URLs.
> S3: exporting minio client

- providers/s3/s3.go
This reverts commit f735308ff69b039c35a24d342e13e402143bf5f6.
> Revert "s3: stat object instead of empty read"

- CHANGELOG.md
- inmem.go
- objstore.go
- providers/azure/azure.go
- providers/bos/bos.go
- providers/cos/cos.go
- providers/filesystem/filesystem.go
- providers/gcs/gcs.go
- providers/obs/obs.go
- providers/oci/oci.go
- providers/oss/oss.go
- providers/s3/s3.go
- providers/swift/swift.go
- testing.go
This pr adds implements `ObjectSize()` method on the return values of `Get` and `GetRange`. This should help readers preallocate buffers based on the content size to reduce number of allocations. They can call `TryToGetSize` on the reader to get the size, existing comment already highlights that this is best effort.
~~I did not add it for swift since the [Length call could potentially result in another request to the server](https://github.com/ncw/swift/blob/master/swift.go#L1741)~~
Updated the acceptance test to check for object size after Get and GetRange calls
> Include content length in the response of Get and GetRange

- CHANGELOG.md
- client/factory.go
- errutil/rt_error.go
- providers/azure/azure.go
- providers/azure/azure_test.go
- providers/azure/helpers.go
- providers/bos/bos.go
- providers/cos/cos.go
- providers/cos/cos_test.go
- providers/gcs/gcs.go
- providers/gcs/gcs_test.go
- providers/obs/obs.go
- providers/oci/oci.go
- providers/oci/oci_test.go
- providers/oss/oss.go
- providers/oss/oss_test.go
- providers/s3/s3.go
- providers/s3/s3_test.go
- providers/swift/swift.go
- providers/swift/swift_test.go
Added a parameter in NewBucket() to pass `wrapRoundtripper func(http.RoundTripper) http.RoundTripper`
Created tests in which a always error returning roundtripper wrapper is passed to NewBucket() and tested whether this error is caught or not.
> Added roundtripper wrapper as param

- CHANGELOG.md
- objstore.go
* fix histogram metrics for `get` and `getrange` operations.
> fix objstore_bucket_operation_duration_seconds metrics

- objstore.go
- objstore_test.go
Adds support for the `io.LimitedReader` in the `TryToGetSize` function.
Added check in type switch for the io.LimitedReader
Added unit test that checks the LimitedReader being supported.
> Support io.LimitedReader in object size check

- CHANGELOG.md
- README.md
- inmem.go
- objstore.go
- prefixed_bucket.go
- prefixed_bucket_test.go
- providers/azure/azure.go
- providers/bos/bos.go
- providers/cos/cos.go
- providers/filesystem/filesystem.go
- providers/filesystem/filesystem_test.go
- providers/gcs/gcs.go
- providers/obs/obs.go
- providers/oci/oci.go
- providers/oss/oss.go
- providers/s3/s3.go
- providers/swift/swift.go
- testing.go
- tracing/opentelemetry/opentelemetry.go
- tracing/opentracing/opentracing.go
Add support for IterWithAttributes
This commit adds support for an IterWithAttributes on the bucket client.
The method allows iterating through objects and getting multiple attributes
into the callback function, removing the need to do an Iter followed by Attrs.
For now, we only support getting the last updated time as an attribute, but the
implementation allows adding more in the future.
Not all buckets support this method. The client can check whether the bucket has
support by calling the SupportedIterOptions method on the client.
Co-authored-by: Ashwanth Goli <iamashwanth@gmail.com>
Co-authored-by: Filip Petkovski <filip.petkovsky@gmail.com>
Signed-off-by: Filip Petkovski <filip.petkovsky@gmail.com>
* Add support for `IterWithAttributes`. 
* Unit tests.
> Add support for object attributes in Iter call

- CHANGELOG.md
- README.md
- client/factory.go
- inmem.go
- objstore.go
- objtesting/foreach.go
- prefixed_bucket.go
- providers/azure/azure.go
- providers/bos/bos.go
- providers/cos/cos.go
- providers/filesystem/filesystem.go
- providers/gcs/gcs.go
- providers/obs/obs.go
- providers/oci/oci.go
- providers/oss/oss.go
- providers/s3/s3.go
- providers/swift/swift.go
- scripts/cfggen/main.go
- testing.go
- tracing/opentelemetry/opentelemetry.go
- tracing/opentracing/opentracing.go
This commit adds a Provider() method to the objstore.Client interface. The method is useful when the client was created from a config file using the client factory.
> Add Provider() method to objstore.Client

- CHANGELOG.md
- objstore.go
- objstore_test.go
- objtesting/acceptance_e2e_test.go
- prefixed_bucket_test.go
- testing.go
Now, when metric bucket got an error which is `isOpFailureExpected`, it doesn't increment the metric but still returns the error back to the caller.
For example, it is quite common to log the error returned by bucket operations like below. However, even if I already specify `IsXXXError` as expected, the error still returns and will be logged. To filter it out, I need to add another `IsXXXError(err)` check to not log the error, which is very redundant to me.
```
err := userBucket.ReaderWithExpectedErrs(IsXXXError).Iter(...)
level.Log("msg", "got error", "err", err)
```
We also have another usecase which doesn't support checking the error in the caller. https://github.com/cortexproject/cortex/blob/master/pkg/storage/bucket/s3/bucket_client.go#L135
We implemented our own storage provider …
> Metric bucket should not return error when error is expected

- CHANGELOG.md
- objstore.go
- objstore_test.go
- objtesting/acceptance_e2e_test.go
- prefixed_bucket_test.go
- testing.go
This reverts commit d69df7208cbace59b1e25d0284b98640045e5749, reversing changes made to 8d266b99071651d4211e4a64fcdfb66da9841929. See [CNCF Slack discussion](https://cloud-native.slack.com/archives/CL25937SP/p1734338085990779?thread_ts=1733878233.511499&cid=CL25937SP) and my [PR comment](https://github.com/thanos-io/objstore/pull/103#issuecomment-2544898326) for context.
> Revert "Merge pull request #103 from thanos-io/do-not-return-error-when-expected"

- providers/oci/oci.go
We are trying to wrap an error which is nil so it ended up return nil.
```
errors.Wrapf(err, fmt.Sprintf("unsupported OCI provider: %s", provider))
```
This caused a panic in Thanos E2E test because `oci.NewTestBucket` tries to reference `bkt` but both bkt and error is nil.
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105c6b138]
goroutine 1705 [running]:
testing.tRunner.func1.2({0x1068c3ce0, 0x107a4c160})
/Users/benye/sdk/go1.23.1/src/testing/testing.go:1632 +0x3c0
testing.tRunner.func1()
/Users/benye/sdk/go1.23.1/src/testing/testing.go:1635 +0x57c
panic({0x1068c3ce0?, 0x107a4c160?}) …
```
> Fix OCI test bucket panic

- CHANGELOG.md
- providers/s3/s3.go
- providers/s3/s3_e2e_test.go
- providers/s3/testdata/encryption_key
Adds missing encryption data passed to `minio.StatObject()` calls, causing client methods `Exists()` and `Attributes()` to fail with a 400 Bad Request error.
This may only affects encryption using `SSE-C` because here it is the callers responsibility to send the encryption key along with the request. In contrast `SSE-KMS` and `SSE-S3` are handled transparently (if the user has permissions to use the key in the casse of `SSE-KMS`)
Fixes #141 
* Add SSE-C configuration to `Bucket.Exists()`
* Add SSE-C configuration to `Bucket.Attributes()`
Added E2E-Test that uploads, checks for existence and downloads a file using SSE-C
> Pass server-side encryption option to minio.StatObject call

- CHANGELOG.md
- client/factory.go
It's handy to be able to create a bucket from an existing BucketConfig object in addition to using raw yaml to do it.
> Add constructor for a client from a BucketConfig object

- README.md
Updated the readme to show the 'prefix' parameter in the OCI config
> Update OCI config example to include 'prefix' parameter.

- inmem.go
- objstore.go
- objstore_test.go
- prefixed_bucket.go
- providers/azure/azure.go
- providers/bos/bos.go
- providers/cos/cos.go
- providers/filesystem/filesystem.go
- providers/gcs/gcs.go
- providers/obs/obs.go
- providers/oci/oci.go
- providers/oss/oss.go
- providers/s3/s3.go
- providers/swift/swift.go
- testing.go
- tracing/opentelemetry/opentelemetry.go
- tracing/opentracing/opentracing.go
I would like to be able to set the content type on uploaded objects since some providers cannot show a preview if the content type is missing.
To facilitate this, I've extended the UploadObject method to accept a variable list of options. The only introduction option is the content type, but it is extensible for other options.
> Add support for object upload options

- objstore.go
- objstore_test.go
The other operations are not exposing the fetched bytes.
> Only register fetched_bytes metrics for Get/GetRange
